"use client";

// import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";
import { useEffect } from "react";
import Lenis from "@studio-freight/lenis";

const dmSans = DM_Sans({
    variable: "--font-dm-sans",
    subsets: ["latin"],
    weight: ["400", "500", "700"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
    children,
}: Readonly<{ children: React.ReactNode }>) {
    useEffect(() => {
        const lenis = new Lenis();

        function raf(time: number) {
            lenis.raf(time);
            requestAnimationFrame(raf);
        }

        requestAnimationFrame(raf);

        return () => {
            lenis.destroy(); // Cleanup on unmount
        };
    }, []);

    return (
        <html lang="en">
            <body className={`${dmSans.variable} antialiased`}>{children}</body>
        </html>
    );
}
